services:
  # A Docker web service
  - type: web
    name: mage-ai
    runtime: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    rootDir: orchestration
    dockerCommand: "docker build -t mage-ai ." # optional (defaults to Dockerfile command)
  # Airbyte service
  - type: web
    name: airbyte
    runtime: python
    region: frankfurt # optional (defaults to oregon)
    plan: free
    rootDir: infra/airbyte
    buildCommand: "pip install -r requirements.txt" # ensure it's a string
    startCommand: "python3 start.py"